// Generated by `libxr gen` from CtrBoard-H7_ALL.ioc and User/libxr_config.yaml.
// Edit only between "User Code Begin" and "User Code End"; the rest is regenerated.
#include "app_main.h"

#include "cdc_uart.hpp"
#include "flash_map.hpp"
#include "libxr.hpp"
#include "main.h"
#include "stm32_adc.hpp"
#include "stm32_canfd.hpp"
#include "stm32_dac.hpp"
#include "stm32_flash.hpp"
#include "stm32_gpio.hpp"
#include "stm32_power.hpp"
#include "stm32_pwm.hpp"
#include "stm32_spi.hpp"
#include "stm32_timebase.hpp"
#include "stm32_uart.hpp"
#include "stm32_usb_dev.hpp"
#include "xrobot_main.hpp"

using namespace LibXR;

/* User Code Begin 1 */
/* User Code End 1 */

extern ADC_HandleTypeDef hadc1;
extern DAC_HandleTypeDef hdac1;
extern FDCAN_HandleTypeDef hfdcan1;
extern FDCAN_HandleTypeDef hfdcan2;
extern FDCAN_HandleTypeDef hfdcan3;
extern PCD_HandleTypeDef hpcd_USB_OTG_HS;
extern SPI_HandleTypeDef hspi2;
extern SPI_HandleTypeDef hspi6;
extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim4;
extern TIM_HandleTypeDef htim12;
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef huart3;
extern UART_HandleTypeDef huart5;
extern UART_HandleTypeDef huart7;
extern UART_HandleTypeDef huart10;

// DMA buffers (STM32H723VG: D-cache, 32-byte lines)
alignas(32) static uint16_t adc1_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t spi2_rx_buf[32] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t spi2_tx_buf[32] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t spi6_rx_buf[32] __attribute__((section(".ram_d3")));
alignas(32) static uint8_t spi6_tx_buf[32] __attribute__((section(".ram_d3")));
alignas(32) static uint8_t uart5_rx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t uart7_rx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t uart7_tx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usart1_rx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usart1_tx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usart2_rx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usart2_tx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usart3_rx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usart3_tx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usart10_rx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usart10_tx_buf[128] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usb_otg_hs_ep0_in_buf[32] __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usb_otg_hs_ep0_out_buf[32]
    __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usb_otg_hs_ep1_in_buf[128]
    __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usb_otg_hs_ep1_out_buf[128]
    __attribute__((section(".axi_ram")));
alignas(32) static uint8_t usb_otg_hs_ep2_in_buf[32] __attribute__((section(".axi_ram")));

extern "C" void app_main(void)
{
  /* User Code Begin 2 */
  /* User Code End 2 */

  // Timebase and platform
  static STM32TimerTimebase timebase(&htim4);
  PlatformInit(static_cast<uint32_t>(Thread::Priority::MEDIUM), 1024);
  static STM32PowerManager power_manager;

  // GPIO
  static STM32GPIO PA15(GPIOA, GPIO_PIN_15);
  static STM32GPIO LCD_BLK(LCD_BLK_GPIO_Port, LCD_BLK_Pin);
  static STM32GPIO LCD_RES(LCD_RES_GPIO_Port, LCD_RES_Pin);
  static STM32GPIO ACC_CS(ACC_CS_GPIO_Port, ACC_CS_Pin);
  static STM32GPIO POWER_24V_2(POWER_24V_2_GPIO_Port, POWER_24V_2_Pin);
  static STM32GPIO PC14(GPIOC, GPIO_PIN_14);
  static STM32GPIO POWER_5V(POWER_5V_GPIO_Port, POWER_5V_Pin);
  static STM32GPIO GYRO_CS(GYRO_CS_GPIO_Port, GYRO_CS_Pin);
  static STM32GPIO ACC_INT(ACC_INT_GPIO_Port, ACC_INT_Pin, EXTI15_10_IRQn);
  static STM32GPIO W25Q64_CS(W25Q64_CS_GPIO_Port, W25Q64_CS_Pin);
  static STM32GPIO GYRO_INT(GYRO_INT_GPIO_Port, GYRO_INT_Pin, EXTI15_10_IRQn);
  static STM32GPIO LCD_CS(LCD_CS_GPIO_Port, LCD_CS_Pin);

  // ADC
  static STM32ADC adc1(&hadc1, adc1_buf, {ADC_CHANNEL_4, ADC_CHANNEL_19}, 3.3);
  static auto& adc1_adc_channel_4 = adc1.GetChannel(0);
  static auto& adc1_adc_channel_19 = adc1.GetChannel(1);

  // DAC
  static STM32DAC dac1_out2(&hdac1, DAC_CHANNEL_2, 0.0, 3.3);

  // PWM
  static STM32PWM pwm_tim1_ch1(&htim1, TIM_CHANNEL_1, false);
  static STM32PWM pwm_tim1_ch3(&htim1, TIM_CHANNEL_3, false);
  static STM32PWM pwm_tim12_ch2(&htim12, TIM_CHANNEL_2, false);
  static STM32PWM pwm_tim2_ch1(&htim2, TIM_CHANNEL_1, false);
  static STM32PWM pwm_tim2_ch3(&htim2, TIM_CHANNEL_3, false);
  static STM32PWM pwm_tim3_ch4(&htim3, TIM_CHANNEL_4, false);

  // SPI, UART, CAN
  static STM32SPI spi2(&hspi2, spi2_rx_buf, spi2_tx_buf, 3);
  static STM32SPI spi6(&hspi6, spi6_rx_buf, spi6_tx_buf, UINT32_MAX);
  static STM32UART uart5(&huart5, uart5_rx_buf, {nullptr, 0}, 5);
  static STM32UART uart7(&huart7, uart7_rx_buf, uart7_tx_buf, 5);
  static STM32UART usart1(&huart1, usart1_rx_buf, usart1_tx_buf, 5);
  static STM32UART usart10(&huart10, usart10_rx_buf, usart10_tx_buf, 5);
  static STM32UART usart2(&huart2, usart2_rx_buf, usart2_tx_buf, 5);
  static STM32UART usart3(&huart3, usart3_rx_buf, usart3_tx_buf, 5);
  static STM32CANFD fdcan1(&hfdcan1, 5);
  LibXR::CAN& can1 = fdcan1;
  static STM32CANFD fdcan2(&hfdcan2, 5);
  LibXR::CAN& can2 = fdcan2;
  static STM32CANFD fdcan3(&hfdcan3, 5);
  LibXR::CAN& can3 = fdcan3;

  // USB OTG HS: 1 CDC
  static constexpr auto usb_otg_hs_strings = USB::DescriptorStrings::MakeLanguagePack(
      USB::DescriptorStrings::Language::EN_US, "QDU-Future", "MainCtrl",
      "QDU-Future-MainCtrl-");
  static USB::CDCUart usb_otg_hs_cdc(USB::Endpoint::EPNumber::EP1,
                                     USB::Endpoint::EPNumber::EP1,
                                     USB::Endpoint::EPNumber::EP2, 128, 128, 3);
  static STM32USBDeviceOtgHS usb_otg_hs(
      &hpcd_USB_OTG_HS, 256, {{usb_otg_hs_ep0_out_buf, 8}, usb_otg_hs_ep1_out_buf},
      {{{usb_otg_hs_ep0_in_buf, 8}, 8},
       {usb_otg_hs_ep1_in_buf, 128},
       {{usb_otg_hs_ep2_in_buf, 16}, 16}},
      USB::DeviceDescriptor::PacketSize0::SIZE_8, 0x1D50, 0x6199, 0xF407,
      {&usb_otg_hs_strings}, {{&usb_otg_hs_cdc}},
      {reinterpret_cast<void*>(UID_BASE), 12});
  usb_otg_hs.Init(false);
  usb_otg_hs.Start(false);

  // Terminal on usb_otg_hs_cdc
  STDIO::read_ = usb_otg_hs_cdc.read_port_;
  STDIO::write_ = usb_otg_hs_cdc.write_port_;
  static RamFS ramfs("XRobot");
  static Terminal<32, 32, 5, 5> terminal(ramfs);
  static Thread term_thread;
  term_thread.Create(&terminal, terminal.ThreadFun, "terminal", 2048,
                     Thread::Priority::MEDIUM);

  // Flash and database
  static STM32Flash flash(FLASH_REGIONS, FLASH_REGION_NUMBER);
  static DatabaseRaw<32> database(flash);

  // Hardware registration
  XR_REGISTER(power_manager, LibXR::PowerManager);

  XR_REGISTER(PA15, LibXR::GPIO);
  XR_REGISTER(LCD_BLK, LibXR::GPIO);
  XR_REGISTER(LCD_RES, LibXR::GPIO);
  XR_REGISTER(ACC_CS, LibXR::GPIO);
  XR_REGISTER(POWER_24V_2, LibXR::GPIO);
  XR_REGISTER(PC14, LibXR::GPIO);
  XR_REGISTER(POWER_5V, LibXR::GPIO);
  XR_REGISTER(GYRO_CS, LibXR::GPIO);
  XR_REGISTER(ACC_INT, LibXR::GPIO);
  XR_REGISTER(W25Q64_CS, LibXR::GPIO);
  XR_REGISTER(GYRO_INT, LibXR::GPIO);
  XR_REGISTER(LCD_CS, LibXR::GPIO);

  XR_REGISTER(adc1_adc_channel_4, LibXR::ADC);
  XR_REGISTER(adc1_adc_channel_19, LibXR::ADC);

  XR_REGISTER(dac1_out2, LibXR::DAC);

  XR_REGISTER(pwm_tim1_ch1, LibXR::PWM);
  XR_REGISTER(pwm_tim1_ch3, LibXR::PWM);
  XR_REGISTER(pwm_tim12_ch2, LibXR::PWM);
  XR_REGISTER(pwm_tim2_ch1, LibXR::PWM);
  XR_REGISTER(pwm_tim2_ch3, LibXR::PWM);
  XR_REGISTER(pwm_tim3_ch4, LibXR::PWM);

  XR_REGISTER(spi2, LibXR::SPI);
  XR_REGISTER(spi6, LibXR::SPI);

  XR_REGISTER(uart5, LibXR::UART);
  XR_REGISTER(uart7, LibXR::UART);
  XR_REGISTER(usart1, LibXR::UART);
  XR_REGISTER(usart10, LibXR::UART);
  XR_REGISTER(usart2, LibXR::UART);
  XR_REGISTER(usart3, LibXR::UART);
  XR_REGISTER(usb_otg_hs_cdc, LibXR::UART);

  XR_REGISTER(can1, LibXR::CAN);
  XR_REGISTER(can2, LibXR::CAN);
  XR_REGISTER(can3, LibXR::CAN);

  XR_REGISTER(fdcan1, LibXR::FDCAN);
  XR_REGISTER(fdcan2, LibXR::FDCAN);
  XR_REGISTER(fdcan3, LibXR::FDCAN);

  XR_REGISTER(ramfs, LibXR::RamFS);

  XR_REGISTER(terminal, LibXR::Terminal<32, 32, 5, 5>);

  XR_REGISTER(database, LibXR::Database);

  /* User Code Begin 3 */
  /* User Code End 3 */
  XROBOT_MAIN();
}
